name: Backfill Books

on:
  workflow_dispatch:  # Manual trigger only

jobs:
  backfill-books:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch full history

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install node-fetch@3 @octokit/rest

      - name: Run backfill script
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GOOGLE_BOOKS_API_KEY: ${{ secrets.GOOGLE_BOOKS_API_KEY }}
        run: node .scripts/backfill_books.js

      - name: Commit and push changes
        run: |
          git config --local user.email "github-actions@github.com"
          git config --local user.name "github-actions"
          git add otaku-archive/books.json
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Backfill books.json with existing issues"
            git push
          fi
