name: Deploy JSON to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      # 3️⃣ Install dependencies
      - name: Install dependencies
        run: npm install gray-matter node-fetch @octokit/rest

      # 4️⃣ Generate JSON files
      - name: Generate blogs, about, and books JSON
        run: node .scripts/generate_json.js

      # 5️⃣ Deploy to GitHub Pages
      - name: Deploy JSON to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./otaku-archive
          user_name: github-actions
          user_email: github-actions@github.com
